### ISSUE TITLE
Suggestions: Validators

### ISSUE THREAD

**Issue by rubit0** [FormsCommunityToolkit/Behaviors#1]
As the title says, what about having validators?

Some ideas:
- valid email address
- not empty
- matches given regex
- is above or below a specific value
- etc.

I think this would be a pretty nifty and usefull thing to have in this Toolkit.
Opinions?

**Comment by bartlannoeye** [comment]
This issue was moved to FormsCommunityToolkit/FormsCommunityToolkit#8
